name: Green
on:
  repository_dispatch:
    types: [Green]
  workflow_dispatch:
jobs:
   Green:
    name: Green
    runs-on: ubuntu-latest
    steps:
      - name: Green
        uses: actions/checkout@v3
      - name: 'Set up Python 3.x'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Green'
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          python app.py
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: 'true'
          branch: 'trunk'
